[package]
name = "shsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
rowan = "0.15.10"
ibig = "0.3.6"

[profile.release]
strip = true
opt-level = "z"
